--SMRDORQ

BEGIN
INSERT INTO ODSMGR.TABLES_TO_CSV (TABLE_NAME, PROCESS_ID, CATEGORY, LAST_REFRESH_TIME, LAST_REFRESH_ROW_COUNT, TOTAL_ROW_COUNT) 
VALUES('SMRDORQ', 'SMRDORQ', 'SATURN', NULL, NULL, 0);
COMMIT;
END;
