--SMRDORQ

--USE ROLE ETL_PROD;
USE DATABASE BI_CDW_DEV;
USE SCHEMA UPN_STG_SIS_BNRODS_ODSMGR;

CREATE OR REPLACE TABLE SMRDORQ (
	SMRDORQ_PIDM FLOAT,
	SMRDORQ_REQUEST_NO FLOAT,
	SMRDORQ_AREA VARCHAR(10),
	SMRDORQ_CAA_SEQNO FLOAT,
	SMRDORQ_GROUP VARCHAR(10),
	SMRDORQ_PROGRAM VARCHAR(12),
	SMRDORQ_TERM_CODE_EFF VARCHAR(6),
	SMRDORQ_MET_IND VARCHAR(1),
	SMRDORQ_SOURCE_IND VARCHAR(1),
	SMRDORQ_ADDL_LEVEL_IND VARCHAR(1),
	SMRDORQ_EXCL_LEVEL_IND VARCHAR(1),
	SMRDORQ_EXCLUSIONS_IND VARCHAR(1),
	SMRDORQ_TRANSFER_IND VARCHAR(1),
	SMRDORQ_SPLIT_COURSE_IND VARCHAR(1),
	SMRDORQ_CNT_IN_GPA_IND VARCHAR(1),
	SMRDORQ_ACTIVITY_DATE TIMESTAMP_NTZ(9),
	SMRDORQ_SET VARCHAR(3),
	SMRDORQ_SUBSET FLOAT,
	SMRDORQ_RULE VARCHAR(10),
	SMRDORQ_SUBJ_CODE VARCHAR(4),
	SMRDORQ_CRSE_NUMB_LOW VARCHAR(5),
	SMRDORQ_CRSE_NUMB_HIGH VARCHAR(5),
	SMRDORQ_ATTR_CODE VARCHAR(4),
	SMRDORQ_ATTS_CODE VARCHAR(4),
	SMRDORQ_CAMP_CODE VARCHAR(3),
	SMRDORQ_COLL_CODE VARCHAR(2),
	SMRDORQ_DEPT_CODE VARCHAR(4),
	SMRDORQ_YEAR_RULE FLOAT,
	SMRDORQ_TERM_CODE_START VARCHAR(6),
	SMRDORQ_TERM_CODE_END VARCHAR(6),
	SMRDORQ_REQ_CREDITS FLOAT,
	SMRDORQ_CONNECTOR_REQ VARCHAR(1),
	SMRDORQ_REQ_COURSES FLOAT,
	SMRDORQ_MAX_CREDITS FLOAT,
	SMRDORQ_CONNECTOR_MAX VARCHAR(1),
	SMRDORQ_MAX_COURSES FLOAT,
	SMRDORQ_MIN_CRED_CRSE FLOAT,
	SMRDORQ_MAX_CRED_CRSE FLOAT,
	SMRDORQ_COMPL_CREDITS FLOAT,
	SMRDORQ_COMPL_COURSES FLOAT,
	SMRDORQ_GRDE_CODE_MIN VARCHAR(6),
	SMRDORQ_MAX_CREDITS_TRANSFER FLOAT,
	SMRDORQ_CONNECTOR_TRANSFER VARCHAR(1),
	SMRDORQ_MAX_COURSES_TRANSFER FLOAT,
	SMRDORQ_ACT_CREDITS FLOAT,
	SMRDORQ_ACT_COURSES FLOAT,
	SMRDORQ_ACT_CREDITS_TRANSFER FLOAT,
	SMRDORQ_ACT_COURSES_TRANSFER FLOAT,
	SMRDORQ_CATALOG_IND VARCHAR(1),
	SMRDORQ_ACTN_CODE VARCHAR(3),
	SMRDORQ_ADJ_CREDITS FLOAT,
	SMRDORQ_ADJ_COURSES FLOAT,
	SMRDORQ_TESC_CODE VARCHAR(6),
	SMRDORQ_MIN_VALUE VARCHAR(15),
	SMRDORQ_MAX_VALUE VARCHAR(15),
	SMRDORQ_CONCURRENCY_IND VARCHAR(1),
	SMRDORQ_SURROGATE_ID FLOAT,
	SMRDORQ_VERSION FLOAT,
	SMRDORQ_USER_ID VARCHAR(30),
	SMRDORQ_DATA_ORIGIN VARCHAR(30),
	SMRDORQ_VPDI_CODE VARCHAR(6)
);

GRANT DELETE,INSERT,REFERENCES,SELECT,TRUNCATE,UPDATE ON TABLE SMRDORQ TO ROLE ADMIN_PROD;
GRANT SELECT ON TABLE SMRDORQ TO ROLE UPN_BI;
GRANT ALL ON TABLE SMRDORQ TO ROLE ETL_PROD;

-------------------------------------------------

--USE ROLE ADMIN_PROD;

USE DATABASE UPN_RPT_DM_DEV;
USE SCHEMA SATURN;

CREATE OR REPLACE VIEW SMRDORQ AS SELECT * FROM BI_CDW_DEV.UPN_STG_SIS_BNRODS_ODSMGR.SMRDORQ;

GRANT ALL ON VIEW SMRDORQ TO ROLE ETL_PROD;
GRANT SELECT ON VIEW SMRDORQ TO ROLE COGNOS_PROD;
GRANT SELECT ON VIEW SMRDORQ TO ROLE UPN_BI;
GRANT SELECT ON VIEW SMRDORQ TO ROLE UPN_READ_PROD;

-------------------------------------------------

--USE ROLE ADMIN_PROD;

USE DATABASE UPN_RPT_DM_DEV;
USE SCHEMA ODSMGR;

CREATE OR REPLACE VIEW SMRDORQ AS SELECT * FROM UPN_RPT_DM_DEV.SATURN.SMRDORQ;

GRANT ALL ON VIEW SMRDORQ TO ROLE ETL_PROD;
GRANT SELECT ON VIEW SMRDORQ TO ROLE COGNOS_PROD;
GRANT SELECT ON VIEW SMRDORQ TO ROLE UPN_BI;
GRANT SELECT ON VIEW SMRDORQ TO ROLE UPN_READ_PROD;

--------------------------------------------------

--USE ROLE ADMIN_PROD;

USE DATABASE BI_CDW_DEV;
USE SCHEMA UPN_STG_SIS_BNRODS_ODSMGR;

BEGIN;
TRUNCATE TABLE UPN_STG_SIS_BNRODS_ODSMGR.SMRDORQ;
ALTER TABLE UPN_STG_SIS_BNRODS_ODSMGR.SMRDORQ
ADD COLUMN ROWNUM NUMBER;
COPY INTO UPN_STG_SIS_BNRODS_ODSMGR.SMRDORQ
FROM @my_s3_stage/SMRDORQ_
PATTERN='.*SMRDORQ_[0-9].*[.]csv'
FILE_FORMAT=my_csv_format
ON_ERROR=CONTINUE;
ALTER TABLE UPN_STG_SIS_BNRODS_ODSMGR.SMRDORQ
DROP COLUMN ROWNUM;
COMMIT;
