BEGIN;
TRUNCATE TABLE UPN_STG_SIS_BNRODS_ODSMGR.SMRDORQ;
ALTER TABLE UPN_STG_SIS_BNRODS_ODSMGR.SMRDORQ
ADD COLUMN ROWNUM NUMBER;
COPY INTO UPN_STG_SIS_BNRODS_ODSMGR.SMRDORQ
FROM @UPN_STAGE_SIS_BNRODS/SMRDORQ_
PATTERN='.*SMRDORQ_[0-9].*[.]csv'
FILE_FORMAT=CSV_UPN_ODS
ON_ERROR=CONTINUE;
ALTER TABLE UPN_STG_SIS_BNRODS_ODSMGR.SMRDORQ
DROP COLUMN ROWNUM;
COMMIT;