--SCRSYLN

USE ROLE ETL_PROD;
USE DATABASE BI_CDW_PROD;
USE SCHEMA UPN_STG_SIS_BNRODS_ODSMGR;

CREATE OR REPLACE TABLE SCRSYLN (
	SCRSYLN_SUBJ_CODE VARCHAR(4),
	SCRSYLN_CRSE_NUMB VARCHAR(5),
	SCRSYLN_TERM_CODE_EFF VARCHAR(6),
	SCRSYLN_ACTIVITY_DATE TIMESTAMP_NTZ(9),
	SCRSYLN_USER_ID VARCHAR(30),
	SCRSYLN_TERM_CODE_END VARCHAR(6),
	SCRSYLN_LONG_COURSE_TITLE VARCHAR(100),
	SCRSYLN_COURSE_URL VARCHAR(100),
	SCRSYLN_SURROGATE_ID FLOAT,
	SCRSYLN_VERSION FLOAT,
	SCRSYLN_DATA_ORIGIN VARCHAR(30),
	SCRSYLN_VPDI_CODE VARCHAR(6)
);

GRANT DELETE,INSERT,REFERENCES,SELECT,TRUNCATE,UPDATE ON TABLE SCRSYLN TO ROLE ADMIN_PROD;
GRANT SELECT ON TABLE SCRSYLN TO ROLE UPN_BI;
GRANT ALL ON TABLE SCRSYLN TO ROLE ETL_PROD;

-------------------------------------------------

USE ROLE ADMIN_PROD;

USE DATABASE UPN_RPT_DM_PROD;
USE SCHEMA SATURN;

CREATE OR REPLACE VIEW SCRSYLN AS SELECT * FROM BI_CDW_PROD.UPN_STG_SIS_BNRODS_ODSMGR.SCRSYLN;

GRANT ALL ON VIEW SCRSYLN TO ROLE ETL_PROD;
GRANT SELECT ON VIEW SCRSYLN TO ROLE COGNOS_PROD;
GRANT SELECT ON VIEW SCRSYLN TO ROLE UPN_BI;
GRANT SELECT ON VIEW SCRSYLN TO ROLE UPN_READ_PROD;

-------------------------------------------------

USE ROLE ADMIN_PROD;

USE DATABASE UPN_RPT_DM_PROD;
USE SCHEMA ODSMGR;

CREATE OR REPLACE VIEW SCRSYLN AS SELECT * FROM UPN_RPT_DM_PROD.SATURN.SCRSYLN;

GRANT ALL ON VIEW SCRSYLN TO ROLE ETL_PROD;
GRANT SELECT ON VIEW SCRSYLN TO ROLE COGNOS_PROD;
GRANT SELECT ON VIEW SCRSYLN TO ROLE UPN_BI;
GRANT SELECT ON VIEW SCRSYLN TO ROLE UPN_READ_PROD;

--------------------------------------------------

USE ROLE ADMIN_PROD;

USE DATABASE BI_CDW_PROD;
USE SCHEMA UPN_STG_SIS_BNRODS_ODSMGR;

BEGIN;
TRUNCATE TABLE UPN_STG_SIS_BNRODS_ODSMGR.SCRSYLN;
ALTER TABLE UPN_STG_SIS_BNRODS_ODSMGR.SCRSYLN
ADD COLUMN ROWNUM NUMBER;
COPY INTO UPN_STG_SIS_BNRODS_ODSMGR.SCRSYLN
FROM @UPN_STAGE_SIS_BNRODS/SCRSYLN_
PATTERN='.*SCRSYLN_[0-9].*[.]csv'
FILE_FORMAT=CSV_UPN_ODS
ON_ERROR=CONTINUE;
ALTER TABLE UPN_STG_SIS_BNRODS_ODSMGR.SCRSYLN
DROP COLUMN ROWNUM;
COMMIT;
