BEGIN;
TRUNCATE TABLE UPN_STG_SIS_BNRODS_ODSMGR.SCRSYLN;
ALTER TABLE UPN_STG_SIS_BNRODS_ODSMGR.SCRSYLN
ADD COLUMN ROWNUM NUMBER;
COPY INTO UPN_STG_SIS_BNRODS_ODSMGR.SCRSYLN
FROM @UPN_STAGE_SIS_BNRODS/SCRSYLN_
PATTERN='.*SCRSYLN_[0-9].*[.]csv'
FILE_FORMAT=CSV_UPN_ODS
ON_ERROR=CONTINUE;
ALTER TABLE UPN_STG_SIS_BNRODS_ODSMGR.SCRSYLN
DROP COLUMN ROWNUM;
COMMIT;