--LOE_AVANCE_CURRICULAR_

USE ROLE ADMIN_PROD;

USE DATABASE UPN_RPT_DM_PROD;
USE SCHEMA ODSMGR;

CREATE OR REPLACE VIEW LOE_AVANCE_CURRICULAR AS SELECT * FROM BI_CDW_PROD.UPN_STG_SIS_BNRODS_ODSMGR.LOE_AVANCE_CURRICULAR;
