--LOE_AVANCE_CURRICULAR_

--USE ROLE ADMIN_PROD;

USE DATABASE UPN_RPT_DM_DEV;
USE SCHEMA ODSMGR;

CREATE OR REPLACE VIEW LOE_AVANCE_CURRICULAR AS SELECT * FROM BI_CDW_DEV.UPN_STG_SIS_BNRODS_ODSMGR.LOE_AVANCE_CURRICULAR;
