--UPDATE_PS_FACTURACION_
--USE ROLE ETL_PROD;
USE DATABASE BI_CDW_DEV;
USE SCHEMA UPN_STG_SIS_BNRODS_ODSMGR;

MERGE INTO PS_FACTURACION USING (
	SELECT
	    Z.BUSINESS_UNIT, Z.PO_REF, Z.PRODUCT, Z.NIVEL, Z.OPERATING_UNIT, Z.CAMPUS, Z.BILL_TO_CUST_ID, Z.NOMBRE_COMPLETO, Z.NOMBRE_COMPLETO_CORPORATE
	    , Z.BILL_TYPE_ID, Z.INSTALL_NBR, Z.INVOICE, Z.LINE_SEQ_NUM, Z.DESCR, Z.SVRSVPR_SRVC_CODE, Z.SVVSRVC_DESC, Z.SVVSRVC_SRCA_CODE, Z.PERIODO_CONTABLE
	    , Z.INVOICE_DT, Z.FECHA_VENCIMIENTO, Z.VAT_RGSTRN_ID, ROUND(Z.NET_EXTENDED_AMT,2) AS NET_EXTENDED_AMT, ROUND(Z.INVOICE_AMOUNT,2) AS INVOICE_AMOUNT
	    , Z.ORIGINAL_INVOICE, Z.ENTRY_TYPE_BI, Z.ACCOUNT_BI, Z.JOURNAL_ID_BI, Z.JOURNAL_DATE_BI, Z.REV_RECOG_BASIS_DESC
	    , ROUND(CASE WHEN Z.MONTO_IMPUESTO <> 0 THEN Z.MONTO_BI_AR_CALCULADO ELSE 0 END,2) AS MONTO_AFECTO
	    , ROUND(CASE WHEN Z.MONTO_IMPUESTO = 0 THEN Z.MONTO_BI_AR_CALCULADO ELSE 0 END,2) AS MONTO_INAFECTO
	    , ROUND(Z.MONTO_IMPUESTO,2) AS MONTO_IMPUESTO, ROUND((Z.MONTO_BI_AR_CALCULADO + Z.MONTO_IMPUESTO),2) AS MONTO_TOTAL
	    , NVL(Z.SUBCATEGORIA1,Z.SUBCATEGORIA2) AS SUBCATEGORIA
	    , CASE
	    	WHEN Z.PERIODO IS NOT NULL AND (NVL(Z.SUBCATEGORIA1,Z.SUBCATEGORIA2) = 'MATRICULA / CUOTA INICIAL' OR SUBSTR(NVL(Z.SUBCATEGORIA1,Z.SUBCATEGORIA2),1,5) = 'CUOTA')
	    			THEN NVL(Z.SUBCATEGORIA1,Z.SUBCATEGORIA2)
	    	WHEN NVL(Z.SUBCATEGORIA1,Z.SUBCATEGORIA2) IN ('EPEC','INGLES') THEN NVL(Z.SUBCATEGORIA1,Z.SUBCATEGORIA2)
	    	WHEN NVL(Z.SUBCATEGORIA1,Z.SUBCATEGORIA2) IN ('INGRESOS POR PAGO ATRASADO','INTERES MORATORIO') THEN 'LATE FEES'
	    	ELSE 'OTROS' END AS CATEGORIA
	    , CASE WHEN Z.PERIODO IS NOT NULL AND (NVL(Z.SUBCATEGORIA1,Z.SUBCATEGORIA2) = 'MATRICULA / CUOTA INICIAL' OR SUBSTR(NVL(Z.SUBCATEGORIA1,Z.SUBCATEGORIA2),1,5) = 'CUOTA')
	    		THEN Z.PERIODO ELSE 'OTROS INGRESOS' END AS PERIODO
	    , Z.START_DATE, Z.END_DATE
	    , CASE WHEN NVL(Z.SUBCATEGORIA1,Z.SUBCATEGORIA2) IN ('INGRESOS POR PAGO ATRASADO','INTERES MORATORIO','SERVICIO','PAGOS ADELANTADOS')
	    			OR (SUBSTR(Z.PO_REF,4,1) IN ('3','4','5') AND TO_CHAR(Z.INVOICE_DT,'YYYY') = TO_CHAR(Z.END_DATE,'YYYY'))
	    		THEN 'Y' ELSE Z.CARTERA_ACTIVA END AS CARTERA_ACTIVA
	    , CURRENT_TIMESTAMP
	FROM (
		SELECT DISTINCT
		    D.BUSINESS_UNIT, D.INVOICE, D.BILL_STATUS, D.BILL_TYPE_ID, D.INVOICE_AMOUNT, D.INVOICE_DT, D.PERIODO_CONTABLE, D.PO_REF
		    , D.TOT_VAT, D.DUE_DT, D.PRODUCT, U.VALUE2 AS NIVEL, D.OPERATING_UNIT, T.VALUE2 AS CAMPUS, D.NET_EXTENDED_AMT, D.ENTRY_TYPE AS ENTRY_TYPE_BI
		    , D.BILL_TO_CUST_ID, REPLACE(CONCAT(CONCAT(I.NAME2,' '),I.NAME1),'/',' ') AS NOMBRE_COMPLETO
		    , I.CORPORATE_CUST_ID, REPLACE(CONCAT(CONCAT(J.NAME2,' '),J.NAME1),'/',' ') AS NOMBRE_COMPLETO_CORPORATE, L.VAT_RGSTRN_ID
		    , NVL(M.INSTALL_NBR,M0.INSTALL_NBR) AS INSTALL_NBR, NVL(M.INVOICE,D.INVOICE) AS INVOICE_PLANTILLA
		    , NVL(SUBSTR(N.TEXT254,LENGTH(N.TEXT254)-9),N0.TEXT254) AS ORIGINAL_INVOICE
		    , CASE WHEN R.DUE_DT IS NULL 
		        THEN ( CASE WHEN D.PYMNT_TERMS_CD IN ('000','0000','00000') 
		            THEN D.DUE_DT 
		            ELSE Q.DUE_DT END ) 
		        ELSE R.DUE_DT END AS FECHA_VENCIMIENTO
		    , D.TOT_VAT AS MONTO_IMPUESTO
		    , CASE WHEN D.BILL_TYPE_ID IN ('F1','B1','D1','D2','C1','C2') 
		        THEN E.MONETARY_AMOUNT *-1
		        ELSE E.MONETARY_AMOUNT END AS MONTO_BI_AR_CALCULADO
		    , E.MONETARY_AMOUNT/*, E.LINE_SEQ_NUM*/, E.ACCOUNT ACCOUNT_BI, E.JOURNAL_ID JOURNAL_ID_BI, E.JOURNAL_DATE JOURNAL_DATE_BI
		    , D.LINE_SEQ_NUM, D.DESCR, D.REV_RECOG_BASIS, S.SVRSVPR_SRVC_CODE, S.SVVSRVC_DESC, S.SVVSRVC_SRCA_CODE
		    , CASE D.REV_RECOG_BASIS 
		            WHEN 'CHG' THEN 'Rango F Inicial/Final' 
		            WHEN 'INV' THEN 'Fecha Factura' ELSE D.REV_RECOG_BASIS END AS REV_RECOG_BASIS_DESC
		    , MAX(CASE
			    	WHEN LENGTH(D.INVOICE) < 10 OR S.SVRSVPR_SRVC_CODE IS NOT NULL OR (E.ACCOUNT = '4800000' AND D.REV_RECOG_BASIS = 'INV') THEN 'SERVICIO'
			    	WHEN E.ACCOUNT = '4119200' THEN 'INGRESOS POR PAGO ATRASADO'
			    	WHEN E.ACCOUNT = '8200000' THEN 'INTERES MORATORIO'
			    	WHEN SUBSTR(D.PO_REF,4,1) IN ('8','9') THEN 'EPEC'
			    	WHEN SUBSTR(D.PO_REF,4,1) = '7' THEN 'INGLES'
			    	WHEN NVL(M.INSTALL_NBR,M0.INSTALL_NBR) IS NOT NULL THEN 'CUOTA ' || NVL(M.INSTALL_NBR,M0.INSTALL_NBR)
			    	WHEN E.ACCOUNT = '4620000' THEN 'INGRESOS POR CAFETERIA'	    	
			    	WHEN E.ACCOUNT = '6332000' THEN 'INTERCOMPANYS'
			    	WHEN E.ACCOUNT = '6551000' THEN 'RECUPEROS'
			    	WHEN E.ACCOUNT = '8350000' THEN 'INGRESOS NO OPERACIONES'
			    	WHEN E.ACCOUNT = '8400000' THEN 'AJUSTE TC GANANCIA/PERDIDA'
			    	WHEN E.ACCOUNT = '8400010' THEN 'AJUSTE POR REDONDEO'
			    	WHEN E.ACCOUNT = '2120000' THEN 'REEMBOLSO A ESTUDIANTE'
			    	WHEN E.ACCOUNT = '2161000' THEN 'PAGOS ADELANTADOS'
			    	WHEN E.ACCOUNT = '1140000' THEN 'CUENTAS POR COBRAR'
			    	ELSE NULL END) OVER(PARTITION BY D.INVOICE) AS SUBCATEGORIA1
		    , MAX(CASE	    	
			    	WHEN E.ACCOUNT IN ('4000000','2160000','4901000','4904000','2160100','2160400') THEN 'MATRICULA / CUOTA INICIAL'
			    	WHEN E.ACCOUNT IN ('4800000','2160080') THEN 'OTROS INGRESOS'
			    	ELSE NULL END) OVER(PARTITION BY D.INVOICE) AS SUBCATEGORIA2
		    , V.SEMESTRE ||' ('|| V.NIVEL ||')' AS PERIODO
		    , W.START_DATE, W.END_DATE, CASE WHEN D.INVOICE_DT > W.END_DATE THEN 'N' ELSE 'Y' END AS CARTERA_ACTIVA    
		FROM ( SELECT DISTINCT 
		            A.BUSINESS_UNIT, A.INVOICE, A.BILL_STATUS, A.BILL_TYPE_ID, A.INVOICE_AMOUNT, A.INVOICE_DT, TO_CHAR(A.INVOICE_DT,'YYYYMM') AS PERIODO_CONTABLE
		            , A.PO_REF, A.TOT_VAT, A.DUE_DT, A.BILL_TO_CUST_ID, A.PYMNT_TERMS_CD, A.ENTRY_TYPE, B.LINE_SEQ_NUM, B.DESCR, B.NET_EXTENDED_AMT, B.REV_RECOG_BASIS
		            , MAX(C.PRODUCT) AS PRODUCT
		            , MAX(C.OPERATING_UNIT) AS OPERATING_UNIT
		        FROM UPN_RPT_DM_DEV.ODSMGR.PS_BI_HDR A, UPN_RPT_DM_DEV.ODSMGR.PS_BI_LINE B, UPN_RPT_DM_DEV.ODSMGR.PS_BI_LINE_DST C
		        WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT AND A.INVOICE = B.INVOICE
		        	AND B.BUSINESS_UNIT = C.BUSINESS_UNIT(+) AND B.INVOICE = C.INVOICE(+) AND B.LINE_SEQ_NUM = C.LINE_SEQ_NUM(+)
		            AND A.BUSINESS_UNIT = 'PER03' --AND A.INVOICE_DT BETWEEN TO_DATE(:FECHA_INICIO,'YYYY-MM-DD') AND TO_DATE(:FECHA_FIN,'YYYY-MM-DD')
		            AND A.INVOICE_DT BETWEEN (CURRENT_TIMESTAMP - INTERVAL '2 months') AND CURRENT_TIMESTAMP
		        GROUP BY A.BUSINESS_UNIT, A.INVOICE, A.BILL_STATUS, A.BILL_TYPE_ID, A.INVOICE_AMOUNT, A.INVOICE_DT, A.PO_REF, A.TOT_VAT, A.DUE_DT
		            , A.BILL_TO_CUST_ID, A.PYMNT_TERMS_CD, A.ENTRY_TYPE, B.LINE_SEQ_NUM, B.DESCR, B.NET_EXTENDED_AMT, B.REV_RECOG_BASIS
		            ) D            
					INNER JOIN UPN_RPT_DM_DEV.ODSMGR.PS_BI_ACCT_ENTRY E ON D.BUSINESS_UNIT = E.BUSINESS_UNIT AND D.INVOICE = E.INVOICE AND D.LINE_SEQ_NUM = E.LINE_SEQ_NUM
															AND D.PERIODO_CONTABLE = TO_CHAR(E.JOURNAL_DATE,'YYYYMM')
															AND E.ACCT_ENTRY_TYPE IN ('DR','RR') AND E.APPL_JRNL_ID = 'BI_BILLING' AND (E.JOURNAL_ID <> ' ' OR E.JOURNAL_ID IS NOT NULL)
															--AND E.JOURNAL_DATE BETWEEN TO_DATE(:FECHA_INICIO,'YYYY-MM-DD') AND TO_DATE(:FECHA_FIN,'YYYY-MM-DD')
					LEFT JOIN UPN_RPT_DM_DEV.ODSMGR.PS_CUSTOMER I ON D.BILL_TO_CUST_ID = I.CUST_ID
					LEFT JOIN UPN_RPT_DM_DEV.ODSMGR.PS_CUSTOMER J ON I.CORPORATE_CUST_ID = J.CUST_ID
					LEFT JOIN UPN_RPT_DM_DEV.ODSMGR.PS_CUST_VAT_REG L ON D.BILL_TO_CUST_ID = L.CUST_ID
					LEFT JOIN UPN_RPT_DM_DEV.ODSMGR.PS_BI_INSTALL_SCHE M ON D.INVOICE = M.GENERATED_INVOICE
					LEFT JOIN UPN_RPT_DM_DEV.ODSMGR.PS_BI_LINE_NOTE N ON D.INVOICE = N.INVOICE AND N.TEXT254 LIKE '%ORIGINAL_INVOICE:%'
														    	AND N.LINE_SEQ_NUM = (SELECT MIN(N1.LINE_SEQ_NUM) FROM UPN_RPT_DM_DEV.ODSMGR.PS_BI_LINE_NOTE N1
																					WHERE N1.BUSINESS_UNIT = N.BUSINESS_UNIT AND N1.INVOICE = N.INVOICE
																						AND N1.TEXT254 LIKE '%ORIGINAL_INVOICE:%')
					LEFT JOIN UPN_RPT_DM_DEV.ODSMGR.PS_BI_LINE_NOTE N0 ON D.INVOICE = N0.INVOICE AND N0.NOTE_TYPE = 'INVOICE'
															AND N0.LINE_SEQ_NUM = (SELECT MIN(N2.LINE_SEQ_NUM) FROM UPN_RPT_DM_DEV.ODSMGR.PS_BI_LINE_NOTE N2
																					WHERE N2.BUSINESS_UNIT = N0.BUSINESS_UNIT AND N2.INVOICE = N0.INVOICE
																						AND N2.NOTE_TYPE = 'INVOICE')
					LEFT JOIN UPN_RPT_DM_DEV.ODSMGR.PS_BI_INSTALL_SCHE M0 ON NVL(SUBSTR(N.TEXT254,LENGTH(N.TEXT254)-9),N0.TEXT254) = M0.GENERATED_INVOICE
					LEFT JOIN UPN_RPT_DM_DEV.ODSMGR.PS_PAY_TRMS_NET P ON D.BUSINESS_UNIT = P.SETID AND D.PYMNT_TERMS_CD = P.PYMNT_TERMS_CD
															AND P.EFFDT = (SELECT MAX(P1.EFFDT) FROM UPN_RPT_DM_DEV.ODSMGR.PS_PAY_TRMS_NET P1
																			WHERE P1.SETID = P.SETID AND P1.PYMNT_TERMS_CD = P.PYMNT_TERMS_CD AND P1.EFFDT <= CURRENT_DATE)
					LEFT JOIN UPN_RPT_DM_DEV.ODSMGR.PS_PAY_TRMS_TIME Q ON P.SETID = Q.SETID AND P.PAY_TRMS_TIME_ID = Q.PAY_TRMS_TIME_ID
					LEFT JOIN UPN_RPT_DM_DEV.ODSMGR.PS_ITEM R ON D.BUSINESS_UNIT = R.BUSINESS_UNIT AND D.INVOICE = R.ITEM AND (R.CUST_ID <> '9999999999' OR R.CUST_ID IS NULL)
					LEFT JOIN ( SELECT DISTINCT ACCOUNT_UID, ID, NAME, CREDIT_CARD_NUMBER
									, SVRSVPR_SRVC_CODE, SVVSRVC_DESC, SVVSRVC_SRCA_CODE
								FROM UPN_RPT_DM_DEV.ODSMGR.RECEIVABLE_ACCOUNT_DETAIL, UPN_RPT_DM_DEV.ODSMGR.LOE_SVRSVPR, UPN_RPT_DM_DEV.ODSMGR.LOE_SVVSRVC
								WHERE ACCOUNT_UID = SVRSVPR_PIDM AND TRANSACTION_NUMBER = SVRSVPR_ACCD_TRAN_NUMBER AND SVRSVPR_SRVC_CODE = SVVSRVC_CODE
									) S ON D.INVOICE = S.CREDIT_CARD_NUMBER AND D.DESCR = S.SVVSRVC_DESC
					LEFT JOIN UPN_RPT_DM_DEV.ODSMGR.LOE_BASE_TABLE_EQUIV T ON D.OPERATING_UNIT = T.VALUE1 AND T.TABLE_PARENT_ID = 1
					LEFT JOIN UPN_RPT_DM_DEV.ODSMGR.LOE_BASE_TABLE_EQUIV U ON D.PRODUCT = U.VALUE1 AND U.TABLE_PARENT_ID = 9
					LEFT JOIN ( SELECT TERM_CODE, SUBSTR(STVTERM_DESC,1,6) AS SEMESTRE, STVTERM_DESC
									, CASE SUBSTR(TERM_CODE,4,1) WHEN '4' THEN 'UG' WHEN '5' THEN 'WA' END AS NIVEL
								FROM UPN_RPT_DM_DEV.ODSMGR.LOE_SECTION_PART_OF_TERM, UPN_RPT_DM_DEV.ODSMGR.STVTERM
								WHERE TERM_CODE = STVTERM_CODE AND WEEKS > 15 AND WEEKS < 18 AND SUBSTR(TERM_CODE,4,1) IN ('4','5') AND TERM_CODE > 217430
									) V ON D.PO_REF = V.TERM_CODE
					LEFT JOIN UPN_RPT_DM_DEV.ODSMGR.LOE_SECTION_PART_OF_TERM W ON D.PO_REF = W.TERM_CODE
		) Z
	) DIF ON PS_FACTURACION.BUSINESS_UNIT = DIF.BUSINESS_UNIT AND PS_FACTURACION.INVOICE = DIF.INVOICE AND PS_FACTURACION.LINE_SEQ_NUM = DIF.LINE_SEQ_NUM
    WHEN MATCHED THEN
		UPDATE SET PS_FACTURACION.BUSINESS_UNIT = DIF.BUSINESS_UNIT
			, PS_FACTURACION.PO_REF = DIF.PO_REF
			, PS_FACTURACION.PRODUCT = DIF.PRODUCT
			, PS_FACTURACION.NIVEL = DIF.NIVEL
			, PS_FACTURACION.OPERATING_UNIT = DIF.OPERATING_UNIT
			, PS_FACTURACION.CAMPUS = DIF.CAMPUS
			, PS_FACTURACION.BILL_TO_CUST_ID = DIF.BILL_TO_CUST_ID
			, PS_FACTURACION.NOMBRE_COMPLETO = DIF.NOMBRE_COMPLETO
			, PS_FACTURACION.NOMBRE_COMPLETO_CORPORATE = DIF.NOMBRE_COMPLETO_CORPORATE
			, PS_FACTURACION.BILL_TYPE_ID = DIF.BILL_TYPE_ID
			, PS_FACTURACION.INSTALL_NBR = DIF.INSTALL_NBR
			, PS_FACTURACION.INVOICE = DIF.INVOICE
			, PS_FACTURACION.LINE_SEQ_NUM = DIF.LINE_SEQ_NUM
			, PS_FACTURACION.DESCR = DIF.DESCR
			, PS_FACTURACION.SVRSVPR_SRVC_CODE = DIF.SVRSVPR_SRVC_CODE
			, PS_FACTURACION.SVVSRVC_DESC = DIF.SVVSRVC_DESC
			, PS_FACTURACION.SVVSRVC_SRCA_CODE = DIF.SVVSRVC_SRCA_CODE
			, PS_FACTURACION.PERIODO_CONTABLE = DIF.PERIODO_CONTABLE
			, PS_FACTURACION.INVOICE_DT = DIF.INVOICE_DT
			, PS_FACTURACION.FECHA_VENCIMIENTO = DIF.FECHA_VENCIMIENTO
			, PS_FACTURACION.VAT_RGSTRN_ID = DIF.VAT_RGSTRN_ID
			, PS_FACTURACION.NET_EXTENDED_AMT = DIF.NET_EXTENDED_AMT
			, PS_FACTURACION.INVOICE_AMOUNT = DIF.INVOICE_AMOUNT
			, PS_FACTURACION.ORIGINAL_INVOICE = DIF.ORIGINAL_INVOICE
			, PS_FACTURACION.ENTRY_TYPE_BI = DIF.ENTRY_TYPE_BI
			, PS_FACTURACION.ACCOUNT_BI = DIF.ACCOUNT_BI
			, PS_FACTURACION.JOURNAL_ID_BI = DIF.JOURNAL_ID_BI
			, PS_FACTURACION.JOURNAL_DATE_BI = DIF.JOURNAL_DATE_BI
			, PS_FACTURACION.REV_RECOG_BASIS_DESC = DIF.REV_RECOG_BASIS_DESC
			, PS_FACTURACION.MONTO_AFECTO = DIF.MONTO_AFECTO
			, PS_FACTURACION.MONTO_INAFECTO = DIF.MONTO_INAFECTO
			, PS_FACTURACION.MONTO_IMPUESTO = DIF.MONTO_IMPUESTO
			, PS_FACTURACION.MONTO_TOTAL = DIF.MONTO_TOTAL
			, PS_FACTURACION.SUBCATEGORIA = DIF.SUBCATEGORIA
			, PS_FACTURACION.CATEGORIA = DIF.CATEGORIA
			, PS_FACTURACION.PERIODO = DIF.PERIODO
			, PS_FACTURACION.START_DATE = DIF.START_DATE
			, PS_FACTURACION.END_DATE = DIF.END_DATE
			, PS_FACTURACION.CARTERA_ACTIVA = DIF.CARTERA_ACTIVA
			, PS_FACTURACION.FECHA_SINCRONIZACION = CURRENT_TIMESTAMP
	WHEN NOT MATCHED THEN
		INSERT (BUSINESS_UNIT, PO_REF, PRODUCT, NIVEL, OPERATING_UNIT, CAMPUS, BILL_TO_CUST_ID, NOMBRE_COMPLETO, NOMBRE_COMPLETO_CORPORATE
			, BILL_TYPE_ID, INSTALL_NBR, INVOICE, LINE_SEQ_NUM, DESCR, SVRSVPR_SRVC_CODE, SVVSRVC_DESC, SVVSRVC_SRCA_CODE
			, PERIODO_CONTABLE, INVOICE_DT, FECHA_VENCIMIENTO, VAT_RGSTRN_ID, NET_EXTENDED_AMT, INVOICE_AMOUNT, ORIGINAL_INVOICE
			, ENTRY_TYPE_BI, ACCOUNT_BI, JOURNAL_ID_BI, JOURNAL_DATE_BI, REV_RECOG_BASIS_DESC, MONTO_AFECTO, MONTO_INAFECTO, MONTO_IMPUESTO
			, MONTO_TOTAL, SUBCATEGORIA, CATEGORIA, PERIODO, START_DATE, END_DATE, CARTERA_ACTIVA, FECHA_SINCRONIZACION)
		VALUES (DIF.BUSINESS_UNIT, DIF.PO_REF, DIF.PRODUCT, DIF.NIVEL, DIF.OPERATING_UNIT, DIF.CAMPUS, DIF.BILL_TO_CUST_ID, DIF.NOMBRE_COMPLETO, DIF.NOMBRE_COMPLETO_CORPORATE
			, DIF.BILL_TYPE_ID, DIF.INSTALL_NBR, DIF.INVOICE, DIF.LINE_SEQ_NUM, DIF.DESCR, DIF.SVRSVPR_SRVC_CODE, DIF.SVVSRVC_DESC, DIF.SVVSRVC_SRCA_CODE
			, DIF.PERIODO_CONTABLE, DIF.INVOICE_DT, DIF.FECHA_VENCIMIENTO, DIF.VAT_RGSTRN_ID, DIF.NET_EXTENDED_AMT, DIF.INVOICE_AMOUNT, DIF.ORIGINAL_INVOICE
			, DIF.ENTRY_TYPE_BI, DIF.ACCOUNT_BI, DIF.JOURNAL_ID_BI, DIF.JOURNAL_DATE_BI, DIF.REV_RECOG_BASIS_DESC, DIF.MONTO_AFECTO, DIF.MONTO_INAFECTO, DIF.MONTO_IMPUESTO
			, DIF.MONTO_TOTAL, DIF.SUBCATEGORIA, DIF.CATEGORIA, DIF.PERIODO, DIF.START_DATE, DIF.END_DATE, DIF.CARTERA_ACTIVA, CURRENT_TIMESTAMP)
;