--UPDATE_PS_ANULACION_
--USE ROLE ETL_PROD;
USE DATABASE BI_CDW_DEV;
USE SCHEMA UPN_STG_SIS_BNRODS_ODSMGR;

CREATE OR REPLACE PROCEDURE UPDATE_PS_ANULACION()
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
    var rs = snowflake.execute( { sqlText: 
        `
	MERGE INTO PS_ANULACION USING (
	SELECT DISTINCT F.BUSINESS_UNIT, F.ITEM, F.ITEM_LINE, F.ITEM_SEQ_NUM, F.ENTRY_TYPE, F.ENTRY_REASON, F.ENTRY_AMT, F.ACCOUNTING_DT
		, F.PERIODO_CONTABLE, G.JOURNAL_ID AS JOURNAL_ID_AR, G.JOURNAL_DATE AS JOURNAL_DATE_AR
	FROM ( SELECT BUSINESS_UNIT, ITEM, ITEM_LINE, ITEM_SEQ_NUM, ENTRY_TYPE, ENTRY_REASON, ENTRY_AMT, ACCOUNTING_DT, TO_CHAR(ACCOUNTING_DT,''YYYYMM'') AS PERIODO_CONTABLE
	            , MAX(CASE WHEN ENTRY_TYPE IN (''WO'',''WOC'') AND ENTRY_REASON = ''A-DIR'' THEN ''WO_WOC_A-DIR'' END) OVER(PARTITION BY ITEM, TO_CHAR(ACCOUNTING_DT,''YYYYMM'')) AS WO_WOC_A_DIR
	        FROM UPN_RPT_DM_DEV.ODSMGR.PS_ITEM_ACTIVITY
	        WHERE BUSINESS_UNIT = ''PER03'' AND ENTRY_TYPE NOT IN (''PY'',''MT'') --AND ACCOUNTING_DT BETWEEN TO_DATE(:FECHA_INICIO,''YYYY-MM-DD'') AND TO_DATE(:FECHA_FIN,''YYYY-MM-DD'')
	        	AND ACCOUNTING_DT BETWEEN (CURRENT_TIMESTAMP - INTERVAL ''2 months'') AND CURRENT_TIMESTAMP
	        ) F
				LEFT JOIN UPN_RPT_DM_DEV.ODSMGR.PS_ITEM_DST G ON F.BUSINESS_UNIT = G.BUSINESS_UNIT AND F.ITEM = G.ITEM AND F.ITEM_LINE = G.ITEM_LINE AND F.ITEM_SEQ_NUM = G.ITEM_SEQ_NUM
													AND F.PERIODO_CONTABLE = TO_CHAR(G.JOURNAL_DATE,''YYYYMM'') AND G.LEDGER = ''ACTUALS''
													--AND G.JOURNAL_DATE BETWEEN TO_DATE(:FECHA_INICIO,''YYYY-MM-DD'') AND TO_DATE(:FECHA_FIN,''YYYY-MM-DD'')
	WHERE F.WO_WOC_A_DIR = ''WO_WOC_A-DIR''
	) DIF ON PS_ANULACION.BUSINESS_UNIT = DIF.BUSINESS_UNIT AND PS_ANULACION.ITEM = DIF.ITEM AND PS_ANULACION.ITEM_SEQ_NUM = DIF.ITEM_SEQ_NUM
    WHEN MATCHED THEN
		UPDATE SET PS_ANULACION.BUSINESS_UNIT = DIF.BUSINESS_UNIT
			, PS_ANULACION.ITEM = DIF.ITEM
			, PS_ANULACION.ITEM_LINE = DIF.ITEM_LINE
			, PS_ANULACION.ITEM_SEQ_NUM = DIF.ITEM_SEQ_NUM
			, PS_ANULACION.ENTRY_TYPE = DIF.ENTRY_TYPE
			, PS_ANULACION.ENTRY_REASON = DIF.ENTRY_REASON
			, PS_ANULACION.ENTRY_AMT = DIF.ENTRY_AMT
			, PS_ANULACION.ACCOUNTING_DT = DIF.ACCOUNTING_DT
			, PS_ANULACION.PERIODO_CONTABLE = DIF.PERIODO_CONTABLE
			, PS_ANULACION.JOURNAL_ID_AR = DIF.JOURNAL_ID_AR
			, PS_ANULACION.JOURNAL_DATE_AR = DIF.JOURNAL_DATE_AR
			, PS_ANULACION.FECHA_SINCRONIZACION = CURRENT_TIMESTAMP
	WHEN NOT MATCHED THEN
		INSERT (BUSINESS_UNIT, ITEM, ITEM_LINE, ITEM_SEQ_NUM, ENTRY_TYPE, ENTRY_REASON, ENTRY_AMT
			, ACCOUNTING_DT, PERIODO_CONTABLE, JOURNAL_ID_AR, JOURNAL_DATE_AR, FECHA_SINCRONIZACION)
		VALUES (DIF.BUSINESS_UNIT, DIF.ITEM, DIF.ITEM_LINE, DIF.ITEM_SEQ_NUM, DIF.ENTRY_TYPE, DIF.ENTRY_REASON, DIF.ENTRY_AMT
			, DIF.ACCOUNTING_DT, DIF.PERIODO_CONTABLE, DIF.JOURNAL_ID_AR, DIF.JOURNAL_DATE_AR, CURRENT_TIMESTAMP);
			`
        } );
    return ''Done.'';
    ';